#if os(macOS)
import Foundation
import WebKit
import XCTest

/// Regenerates `CFIGoldenVectors.swift` by running the vendored foliate-js (`epubcfi.js`,
/// `search.js`, `text-walker.js`, and `epub.js`'s spine and `resolveCFI` code, extracted
/// verbatim) on `CFIFixtures` in WebKit, parsing documents as foliate did. Opt in, because the
/// output is committed and the vendored bundle is to be removed:
/// `EPUBLIB_GENERATE_CFI_VECTORS=1 swift test --filter CFIVectorGenerator`.
@MainActor final class CFIVectorGenerator: XCTestCase {
    private static let sourceRoot = URL(fileURLWithPath: #filePath)
        .deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent().deletingLastPathComponent()

    func testGenerateGoldenVectors() async throws {
        guard ProcessInfo.processInfo.environment["EPUBLIB_GENERATE_CFI_VECTORS"] == "1" else {
            throw XCTSkip("set EPUBLIB_GENERATE_CFI_VECTORS=1 to regenerate CFIGoldenVectors.swift")
        }
        let script = try Self.harness()
        let webView = WKWebView()
        let result = try await webView.evaluateJavaScript(script)
        let json = try XCTUnwrap(result as? String, "the harness returned \(String(describing: result))")
        XCTAssertNotNil(try JSONSerialization.jsonObject(with: Data(json.utf8)))
        let body = json.split(separator: "\n", omittingEmptySubsequences: false).map { "    " + $0 }.joined(separator: "\n")
        let source = """
            // Generated by CFIVectorGenerator from the vendored foliate-js running in WebKit. Do not edit.
            // Regenerate: EPUBLIB_GENERATE_CFI_VECTORS=1 swift test --filter CFIVectorGenerator

            enum CFIGoldenVectors {
                static let json = ##\"\"\"
            \(body)
                \"\"\"##
            }

            """
        let destination = Self.sourceRoot.appending(path: "Tests/EPUBViewingTests/Native/CFIGoldenVectors.swift")
        try Data(source.utf8).write(to: destination)
    }

    private static func library(_ name: String) throws -> String {
        try String(contentsOf: sourceRoot.appending(path: "Sources/EPUBViewing/Resources/epub-reader/\(name)"),
                   encoding: .utf8)
    }

    /// The text from `start` through the first `end` after it, so the harness runs foliate's own code.
    private static func extract(_ source: String, from start: String, through end: String) throws -> String {
        let begin = try XCTUnwrap(source.range(of: start), "vendored source lacks \(start)")
        let finish = try XCTUnwrap(source.range(of: end, range: begin.lowerBound..<source.endIndex),
                                   "vendored source lacks \(end) after \(start)")
        return String(source[begin.lowerBound..<finish.upperBound])
    }

    /// An ES module as a script: its `export`s become an object of the names listed.
    private static func module(_ source: String, exports: String) -> String {
        let body = source.replacing(#/(?m)^export /#, with: "")
        return "(() => {\n\(body)\nreturn { \(exports) }\n})()"
    }

    private static let cfiExports = "parse, stringify: toString, toInnerString, collapse, compare, buildRange, "
        + "fromRange, toRange, fromElements, toElement, partsToNode, indexChildNodes, isCFI, joinIndir"

    private static func harness() throws -> String {
        let epub = try library("lib/epub.js")
        let ns = try extract(epub, from: "const NS = {", through: "\n}\n")
        let helpers = try extract(epub, from: "const camel = ", through: "\n}\n\nconst resolveURL")
            .replacingOccurrences(of: "\n\nconst resolveURL", with: "\n")
        let spine = try extract(epub, from: "const { $, $$, $$$ } = childGetter(opf, NS.OPF)",
                                through: "const $$itemref = $$($spine, 'itemref')")
        let spineItems = try extract(epub, from: "this.spine = $$itemref", through: "item.properties?.split(/\\s/), item))")
        let cfis = try extract(epub, from: "this.cfis = CFI.fromElements($$itemref)", through: "($$itemref)")
        let resolve = try extract(epub, from: "resolveCFI(cfi) {\n        const parts = CFI.parse(cfi)", through: "\n    }\n")
        let normalize = try extract(try library("bootstrap.js"), from: "const normalizeLocateWhitespace = quote =>",
                                    through: ".trim()")
        let input: [String: Any] = [
            "documents": CFIFixtures.documents.map {
                ["name": $0.name, "xhtml": $0.xhtml, "quotes": $0.quotes, "cfis": $0.cfis + CFIFixtures.commonCFIs]
            },
            "packages": CFIFixtures.packages.map { ["name": $0.name, "opf": $0.opf, "cfis": $0.cfis] },
            "strings": CFIFixtures.strings,
            "pairs": CFIFixtures.pairs.map { [$0.0, $0.1] },
            "collationRanges": CFIFixtures.collationRanges.map { [$0.lowerBound, $0.upperBound] },
            "collationLocales": CFIFixtures.collationLocales,
        ]
        let inputJSON = try XCTUnwrap(String(data: try JSONSerialization.data(withJSONObject: input), encoding: .utf8))
        return """
            (() => {
            "use strict";
            const input = \(inputJSON);
            const CFI = \(module(try library("lib/epubcfi.js"), exports: Self.cfiExports));
            const Search = \(module(try library("lib/search.js"), exports: "search, searchMatcher"));
            const Walker = \(module(try library("lib/text-walker.js"), exports: "textWalker"));
            const Epub = (() => {
            \(ns)
            \(helpers)
            class Resources {
                constructor({ opf }) {
                    this.opf = opf
                    \(spine)
                    \(spineItems)
                    \(cfis)
                }
                \(resolve)
            }
            return { Resources }
            })();
            \(normalize)
            \(Self.driver)
            })()
            """
    }

    /// Runs the vectors. Positions are reported in `ContentDocument`'s model of the DOM (elements
    /// and merged character data in preorder) as `[order, offset]`, so the Swift side can compare.
    private static let driver = #"""
        const XHTML = 'http://www.w3.org/1999/xhtml'
        const out = { userAgent: navigator.userAgent, documents: [], packages: [], strings: [], pairs: [], collation: {} }

        // epub.js `loadDocument`: XHTML, re-read as HTML when it is not well-formed or has no namespace.
        const parseDocument = str => {
            const doc = new DOMParser().parseFromString(str, 'application/xhtml+xml')
            if (doc.querySelector('parsererror') || !doc.documentElement?.namespaceURI)
                return { doc: new DOMParser().parseFromString(str, 'text/html'), parser: 'html' }
            return { doc, parser: 'xhtml' }
        }

        const buildModel = doc => {
            const nodes = [], info = new Map()
            const build = el => {
                const order = nodes.length
                const record = { order, base: 0 }
                nodes.push({ kind: 'E', el }); info.set(el, record)
                let pending = null
                const flush = () => {
                    if (!pending) return
                    pending.order = nodes.length; nodes.push(pending)
                    for (const part of pending.parts) info.set(part.node, { order: pending.order, base: part.base })
                    pending = null
                }
                for (const child of el.childNodes) {
                    if (child.nodeType === 1) { flush(); build(child) }
                    else if (child.nodeType === 3 || child.nodeType === 4) {
                        pending ??= { kind: 'T', text: '', parts: [] }
                        pending.parts.push({ node: child, base: pending.text.length })
                        pending.text += child.nodeValue
                    }
                }
                flush()
                record.subtreeEnd = nodes.length - 1
            }
            build(doc.documentElement)
            return { nodes, info }
        }

        const nameOf = el => el.namespaceURI === XHTML ? el.localName.toLowerCase() : el.localName
        const serialize = nodes => nodes.map(n => n.kind === 'E' ? ['E', nameOf(n.el), n.el.namespaceURI ?? ''] : ['T', n.text])
        const before = (a, b) => a[0] !== b[0] ? a[0] < b[0] : a[1] < b[1]

        const runDocument = d => {
            const { doc, parser } = parseDocument(d.xhtml)
            const { nodes, info } = buildModel(doc)
            const result = { name: d.name, parser, model: serialize(nodes) }
            const reparsed = parseDocument(new XMLSerializer().serializeToString(doc))
            result.serializationStable = JSON.stringify(serialize(buildModel(reparsed.doc).nodes)) === JSON.stringify(result.model)

            const orderOf = node => info.get(node).order
            const modelStart = node => node.nodeType === 1 ? [orderOf(node), 0] : [info.get(node).order, info.get(node).base]
            const endOfDocument = () => {
                const last = nodes.length - 1
                return [last, nodes[last].kind === 'T' ? nodes[last].text.length : 0]
            }
            const afterSubtree = el => {
                const end = info.get(el).subtreeEnd
                return end + 1 < nodes.length ? [end + 1, 0] : endOfDocument()
            }
            const isModel = n => n.nodeType === 1 || n.nodeType === 3 || n.nodeType === 4
            const readingOffset = (container, offset) => {
                const range = doc.createRange()
                range.setStart(doc, 0)
                range.setEnd(container, offset)
                return range.toString().length
            }
            const domPoint = ([order, offset]) => {
                const n = nodes[order]
                if (n.kind === 'E') return [n.el, offset]
                for (const part of n.parts)
                    if (part.base + part.node.nodeValue.length >= offset) return [part.node, offset - part.base]
            }

            // fromRange over element starts and each text node's start, middle and end.
            const positions = []
            nodes.forEach((n, order) => {
                if (order === 0) return
                if (n.kind === 'E') positions.push([order, 0])
                else for (const offset of new Set([0, n.text.length >> 1, n.text.length])) positions.push([order, offset])
            })
            const pairs = []
            for (let i = 0; i < positions.length; i++) {
                pairs.push([i, i])
                if (i + 1 < positions.length) pairs.push([i, i + 1])
                if (i + 4 < positions.length) pairs.push([i, i + 4])
            }
            if (positions.length > 1) pairs.push([0, positions.length - 1])
            let seed = 12345
            const random = n => (seed = (seed * 1103515245 + 12345) % 2147483648) % n
            for (let k = 0; k < 30 && positions.length; k++) {
                const a = random(positions.length), b = random(positions.length)
                pairs.push(a <= b ? [a, b] : [b, a])
            }
            result.fromRange = []
            const cfis = new Set()
            for (const [i, j] of pairs) {
                const range = doc.createRange()
                range.setStart(...domPoint(positions[i]))
                range.setEnd(...domPoint(positions[j]))
                let cfi = null
                try { cfi = CFI.fromRange(range); cfis.add(cfi) } catch (e) {}
                result.fromRange.push([...positions[i], ...positions[j], cfi])
            }

            // toRange: foliate's DOM range as reading offsets, and the positions the port must
            // produce: `partsToNode`'s own result, mapped as `EPUBCFI` documents, with stale or
            // missing chunk offsets clamped (foliate threw there; flagged).
            const clampOffset = (path, flags) => {
                const last = path[path.length - 1]
                if (!last || (last.id && doc.getElementById(last.id))) return path
                let node = doc.documentElement
                for (const { index } of path) {
                    let slots = null
                    try { slots = node ? CFI.indexChildNodes(node) : null } catch (e) { return path }
                    const next = slots ? slots[index] : null
                    if (typeof next === 'string') return path
                    node = next
                }
                if (node == null) return path
                const texts = Array.isArray(node) ? node : node.nodeType === 3 || node.nodeType === 4 ? [node] : null
                if (!texts) {
                    if (last.offset) flags.push('elementOffset')
                    return path
                }
                if (last.offset == null && !Array.isArray(node)) return path
                const total = texts.reduce((sum, n) => sum + n.nodeValue.length, 0)
                const clamped = last.offset == null ? 0 : Math.min(last.offset, total)
                if (clamped === last.offset) return path
                flags.push(last.offset == null ? 'missingOffset' : 'staleOffset')
                return path.slice(0, -1).concat({ ...last, offset: clamped })
            }
            const target = (resolved, flags) => {
                if (!resolved || resolved.node == null) return null
                const { node, offset } = resolved
                if (resolved.before) return [orderOf(node), 0]
                if (resolved.after) return afterSubtree(node)
                if (node.nodeType === 1) return [orderOf(node), 0]
                if (node.nodeType === 3 || node.nodeType === 4) {
                    const m = info.get(node)
                    return [m.order, m.base + Math.min(offset ?? 0, node.nodeValue.length)]
                }
                // A comment or processing instruction, from `firstChild` or `lastChild`.
                for (let next = node.nextSibling; next; next = next.nextSibling) if (isModel(next)) return modelStart(next)
                flags.push('trailingNonModelChild')
                for (let previous = node.previousSibling; previous; previous = previous.previousSibling)
                    if (isModel(previous)) return modelStart(previous)
                return [orderOf(node.parentNode), 0]
            }
            result.toRange = []
            for (const cfi of [...cfis, ...d.cfis]) {
                const vector = { cfi, flags: [] }
                result.toRange.push(vector)
                let parts
                try { parts = CFI.parse(cfi) } catch (e) { vector.expected = null; continue }
                try {
                    const range = CFI.toRange(doc, parts)
                    vector.reading = [readingOffset(range.startContainer, range.startOffset),
                                      readingOffset(range.endContainer, range.endOffset)]
                } catch (e) { vector.reading = null }
                try {
                    const ends = [CFI.collapse(parts)[0], CFI.collapse(parts, true)[0]]
                        .map(path => target(CFI.partsToNode(doc.documentElement, clampOffset(path, vector.flags)), vector.flags))
                    vector.expected = ends[0] && ends[1]
                        ? (before(ends[1], ends[0]) ? [...ends[1], ...ends[1]] : [...ends[0], ...ends[1]]) : null
                } catch (e) { vector.expected = null }
            }

            // search.js as the reader's `locate` ran it: `view.search({ query })`, whose
            // `defaultLocale` was foliate's language object rather than a locale string.
            result.search = []
            const lang = doc.body ? doc.body.lang || doc.documentElement.lang : null
            const locale = lang || `default:${new Intl.Collator().resolvedOptions().locale}`
            for (const quote of d.quotes) {
                const query = normalizeLocateWhitespace(quote)
                const vector = { quote, query, locale }
                try {
                    const matcher = Search.searchMatcher(Walker.textWalker, { defaultLocale: { canonical: 'en' }, query })
                    vector.matches = Array.from(matcher(doc, query), ({ range }) => [
                        ...modelStart(range.startContainer).map((x, k) => k ? x + range.startOffset : x),
                        ...modelStart(range.endContainer).map((x, k) => k ? x + range.endOffset : x),
                        CFI.fromRange(range)])
                } catch (e) { vector.error = String(e) }
                result.search.push(vector)
            }
            return result
        }
        for (const d of input.documents) out.documents.push(runDocument(d))

        for (const p of input.packages) {
            const vector = { name: p.name }
            out.packages.push(vector)
            const opf = new DOMParser().parseFromString(p.opf, 'application/xml')
            let resources
            try { resources = new Epub.Resources({ opf }) } catch (e) { vector.error = String(e); continue }
            vector.bases = resources.cfis
            vector.resolve = []
            for (const cfi of new Set([...resources.cfis, ...resources.cfis.map(b => CFI.joinIndir(b, '/4/2/1:3')), ...p.cfis])) {
                let index = null, local = null
                try {
                    index = resources.resolveCFI(cfi).index
                    const rest = CFI.parse(cfi)
                    ;(rest.parent ?? rest).shift()
                    local = CFI.toInnerString(rest)
                } catch (e) {}
                vector.resolve.push([cfi, index != null && index >= 0 ? index : null, local])
            }
        }

        const sortedJSON = value => JSON.stringify(value, (key, v) => v && typeof v === 'object' && !Array.isArray(v)
            ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => a < b ? -1 : 1)) : v)
        for (const s of input.strings) {
            const vector = { input: s, isCFI: CFI.isCFI.test(s), parsed: null, string: null, collapsed: null }
            try {
                const parsed = CFI.parse(s)
                vector.parsed = sortedJSON(parsed)
                vector.string = CFI.stringify(parsed)
            } catch (e) {}
            try { vector.collapsed = [CFI.collapse(s), CFI.collapse(s, true)] } catch (e) {}
            out.strings.push(vector)
        }
        for (const [a, b] of input.pairs) {
            let order = null, range = null
            try { order = CFI.compare(a, b) } catch (e) {}
            try { range = CFI.buildRange(a, b) } catch (e) {}
            out.pairs.push([a, b, order, range])
        }

        const scalars = []
        for (const [low, high] of input.collationRanges)
            for (let c = low; c <= high; c++) if (!/\p{Cn}/u.test(String.fromCodePoint(c))) scalars.push(c)
        for (const locale of input.collationLocales) {
            const collator = new Intl.Collator(locale, { sensitivity: 'base' })
            const chars = scalars.map(c => String.fromCodePoint(c))
            const ignorable = chars.filter(c => collator.compare(c, '') === 0)
            const classes = []
            for (const c of chars.filter(c => collator.compare(c, '') !== 0).sort(collator.compare)) {
                const last = classes[classes.length - 1]
                if (last && collator.compare(last[0], c) === 0) last.push(c)
                else classes.push([c])
            }
            out.collation[locale] = {
                resolved: collator.resolvedOptions().locale,
                ignorable: ignorable.map(c => c.codePointAt(0)),
                classes: classes.filter(c => locale === 'en' || c.length > 1).map(c => c.map(x => x.codePointAt(0))),
            }
        }

        // One vector per line, everything outside ASCII escaped.
        const lines = (value, depth) => depth === 0 || value === null || typeof value !== 'object'
            ? JSON.stringify(value)
            : Array.isArray(value) ? '[\n' + value.map(v => lines(v, depth - 1)).join(',\n') + '\n]'
            : '{\n' + Object.entries(value).map(([k, v]) => JSON.stringify(k) + ': ' + lines(v, depth - 1)).join(',\n') + '\n}'
        return lines(out, 4).replace(/[\u007f-￿]/g, c => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'))
        """#
}
#endif
